# Data Manipulation - Manipulação dos Dados

* Lembrete de como ativar o miniconda: conda activate d2l
* Para desativar: conda deactivate

Formas de armazenar e manipular os dados que iremos utilizar. Para armezanar esses dados podemos utilizar _vetores n-dimensionais_ chamados de **Tensors**.  Para isso, iremos utilizar bastante a biblioteca NumPy:

[Guia inicial da biblioteca NumPy.](https://numpy.org/devdocs/user/quickstart.html)

**PyTorch** - É um conjunto de ferramentas, bibliotecas e outras coisas que fornece uma estrutura para o desenvolvimento de modelos de IA. É baseado na estrutura dos tensores, citados anteriormente, e fornece várias tools para trabalhar com os dados nesse formato. O tensor apresenta algumas similaridades com os arrays do NumPy.

Súmario:
- Começando:
    - Como criar tensores;
- Index e Fatias:
    - Como selecionar os elementos;
    - Indexação;
    - Fatias;
- Operações:
    - Realizar operações com os dados dos tensores;

## Começando:

In [42]:
import torch # Estou importanto esse conjunto de ferramentas citado;

Um tensor pode ser classificado como um vetor, uma matriz ou um objeto de k<sup>th</sup> order-tensor. Veja abaixo algumas operações:

In [43]:
x = torch.arange(12, dtype=torch.float32) 
# Cria um tensor com valores de 0 a 11, com tipo de float;

y = torch.arange(10, 100, 4, dtype=int)
# Cria um tensor com valores inteiros de 10 a 100 dando um step de 4;

print(x)
print(y)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
tensor([10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 70, 74, 78,
        82, 86, 90, 94, 98])


Para saber qual o número de elementos de um tensor:

In [44]:
print(x.numel()) # Informa o número de elementos;
print(y.numel()) 

12
23


Para acessar o comprimento de um tensor ao longo do eixo x:

In [45]:
# Para acessar o comprimento de um tensor ao lonfgo do eixo x:
x.shape

torch.Size([12])

Para mudar o formato de um tensor:

In [46]:
X = x.reshape(3, 4)
print(X) # O tamanho deve continuar o mesmo 12 = 3.4;

# Para não ter que especificar o tamanho, podemos usar o -1 no lugar do valor 
# que queremos que seja calculado automaticamente.


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [47]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [48]:
torch.ones((3, 4, 3))

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

Para iniciar um tensor de parâmetros aleatórios (que é como começa os parâmetros de uma rede neural geralmente) podemos fazer:

In [49]:
torch.randn(5, 4)# Os valores vem de uma distribuição normal.


tensor([[ 0.9847,  0.5872, -0.5087,  0.3999],
        [-0.5448,  1.0212,  0.8948,  0.8965],
        [ 0.7884, -1.0708,  0.2646,  0.8684],
        [ 2.3392,  0.4376,  0.3141,  0.3058],
        [-0.7355,  1.0249, -0.5375,  0.6353]])

Podemos também criar um tensor especificando os elementos:

In [50]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## Index e Fatias:

Para acessar, podemos fazer como uma lista normal do Python. O primeiro elemento começa em zero. Para acessar a partir do final pode-se usar valores negativos. E também é possível cortar fatias:

In [51]:
print(X[0])
print(X[1:3])
print(X[-1])

tensor([0., 1., 2., 3.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([ 8.,  9., 10., 11.])


Elementos da matriz por índices:

In [52]:
print(X[-1, 2])
X[-1, 2] = 499 # Mudando o valor
print(X[-1, 2])

tensor(10.)
tensor(499.)


Também é possível mudar tudo com fatias:

In [53]:
X[:2, 1:3] = 42 # Da 0 até a 1 linha, preencher os elementos da posição 1 até a 2 com 12;
X

tensor([[  0.,  42.,  42.,   3.],
        [  4.,  42.,  42.,   7.],
        [  8.,   9., 499.,  11.]])

## Operações

Agora que sabemos criar e selecionar os dados dos tensores, podemos começar a fazer operações com os mesmos. 