# Álgebra Linear


## Escalares

Notações para valores escalares:

$$ x, y, z \in \mathbb{R} $$

Escalares são implementados em tensores que contém apenas um elemento.

In [17]:
import torch
x = torch.tensor(3.0)
y = torch.tensor(4.0)

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x ** y)

tensor(7.)
tensor(-1.)
tensor(12.)
tensor(0.7500)
tensor(81.)


## Vetores


[Como escrever vetores e matrizes em Markdown](https://definirtec.com/latex-criando-uma-matriz-como-faze-lo/)

Vetores são como listas de escalares. Os valores da lista são os elementos, entradas. NO exemplo abaixo, $a, b$ e $c$ seriam os escalares, entradas, do vetor:

$$ v = 
\begin{bmatrix} 
a \\
b \\
c \\
\end{bmatrix} $$

Vetores são tensores de primeira ordem, e é importante lembrar que a indexação na maioria das linguagens de programação começa em zero enquanto em conteúdos teóricos é mais comum começar em um. 

In [18]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Seja o vetor:

$$ v = 
\begin{bmatrix} 
x_1\\
\vdots \\
x_n\\
\end{bmatrix} $$

Onde $x_1$ representa o primeiro elemento e $x_n$ representa o enésimo do vetor v. Dizemos que $x \in \mathbb{R}^n$, ou seja, $x$ tem $n$ dimensões, $n$ entradas. 

Esse valor é chamado de *dimensionalidade* do vetor. Para saber a *dimensionalidade* de um vetor no Python, basta a função abaixo:

In [19]:
print(len(x))

10


Para verificar a forma, temos a função abaixo. Ela indica em uma tupla o comprimeto de cada eixo do vetor. No nosso exemplo, no qual o vetor só tem um eixo com 10 elementos, o valor resultante é 10:

In [20]:
x.shape

torch.Size([10])

Para não ficar confuso, geralmente utiliza-se de *order* (Ordem) para indicar quantos eixos o vetor pode ter e *dimensionalidade* fica para referenciar a quantidade de elementos. 

## Matrizes:

Matrizes são vetores de segunda ordem, ou seja, possuem dois eixos. Podemos representar uma matriz a partir de um vetor utilizando a função reshape. 

Veja abaixo o código do reshape e a representação de uma matriz $A \in \mathbb{R}^{n * m}$


$$ A =

\begin{pmatrix*}[r] 
a_{11} & a_{12} & \dots & a_{1n} \\
a_{21} & a_{22} & \dots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \dots & a_{mn} \\
\end{pmatrix*} $$


In [21]:
A = torch.arange(18).reshape(3, 6)
print(A)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]])


Para fazer a **transposta** de uma matriz, que é tratar as linhas como colunas e as colunas como linhas, basta:

In [22]:
print(A.T)

tensor([[ 0,  6, 12],
        [ 1,  7, 13],
        [ 2,  8, 14],
        [ 3,  9, 15],
        [ 4, 10, 16],
        [ 5, 11, 17]])


**Matrizes Simétricas** são aquelas que são iguais as suas transpostas. Ou seja $A = A^{T}$. Veja como verificar isso:

In [23]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
print(A == A.T)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


## Tensores:

Além de vetores de primeira e segunda ordem (matrizes), será necessário trabalhar com vetores de odens maiores. Um exemplo de dado que utiliza um vetor de terceira ordem são os dados relativos a imagens:
- Altura;
- Largura;
- Channel - que guarda a intensidade de cada cor (RGB - Red, Green e Blue);

Esse é só um exemplo de como podemos trabalhar com imagens e a motivação por de trás da necessidade de tensores de ordens maiores. Veja abaixo um tensor de 3º ordem:

In [24]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

É como se fosse um paralelepipedo com cada camada sendo uma matriz, e tendo no total, 2 dessas camadas de matriz. Como se fosse uma fila de matrizes. 

## Propriedades Básicas de Aritmética de Tensores

Veremos algumas operações básicas com tensores:

#### Soma:

In [26]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Copia A em B, alocando uma nova memória; 

print(A)

print("A + B = ", A + B)
print("2 * A = ", 2*A)


tensor([[0., 1., 2.],
        [3., 4., 5.]])
A + B =  tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])
2 * A =  tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])


#### Hadamard Product:

Multiplica o elemento $a_{ijk...}$ pelo elemento $b_{ijk...}$ e forma um novo tensor. É chamado de Hadamard Product:

In [27]:
print("A * B = ", A * B)

A * B =  tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])


#### Operações de Tensor com Escalar:

As operações são realizadas somando, subtraindo, dividindo ou multiplicando o escapar por todo elemento do tensor. Veja abaixo um exemplo da multipliação:

In [28]:
C = torch.arange(24).reshape(2, 3, 4)
print(C)

print("C * 100 = ", C * 100)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
C * 100 =  tensor([[[   0,  100,  200,  300],
         [ 400,  500,  600,  700],
         [ 800,  900, 1000, 1100]],

        [[1200, 1300, 1400, 1500],
         [1600, 1700, 1800, 1900],
         [2000, 2100, 2200, 2300]]])


## Reduction - Redução:


Calcular a soma de todos os elementos de um vetor de dimensionalidade $n$:

$$\sum_{i=1}^{n} x_i$$

Para obter esse valor, tem uma função pronta:

In [30]:
X = torch.arange(50, dtype=float)
X[:] = X + 1
print(X)
print(X.sum())

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28.,
        29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42.,
        43., 44., 45., 46., 47., 48., 49., 50.], dtype=torch.float64)
tensor(1275., dtype=torch.float64)


Para um tensor de forma arbitrária, a soma devolve a soma de todos os elementos do tensor:

In [35]:
Y = torch.arange(36).reshape(3, 2, 6)
Y[:] = Y + 1
print(Y)

print(Y.sum())

tensor([[[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12]],

        [[13, 14, 15, 16, 17, 18],
         [19, 20, 21, 22, 23, 24]],

        [[25, 26, 27, 28, 29, 30],
         [31, 32, 33, 34, 35, 36]]])
tensor(666)


É possível também especificar em quais eixos se deseja realizar a soma, para isso, basta especificar por meio do índice do eixo:

In [43]:
print(Y.shape)
print(Y.sum(axis=0)) # Ao longo do eixo z; (3)
print(Y.sum(axis=1)) # Ao longo do eixo y; (2)
print(Y.sum(axis=2)) # Ao longo do eixo x; (6)

torch.Size([3, 2, 6])
tensor([[39, 42, 45, 48, 51, 54],
        [57, 60, 63, 66, 69, 72]])
tensor([[ 8, 10, 12, 14, 16, 18],
        [32, 34, 36, 38, 40, 42],
        [56, 58, 60, 62, 64, 66]])
tensor([[ 21,  57],
        [ 93, 129],
        [165, 201]])
